export { ArticleDetailsPageLazy } from './ui/ArticleDetailsPage/ArticleDetailsPage.lazy'
export { ICommentsSchema } from './model/types/commentsSchema'
export { IArticleDetailsRecommendationsSchema } from './model/types/recommendationsSchema'
export { IArticleDetailsPageSchema } from './model/types/index'
export { articleDetailsPageReducer } from './model/slice/index'