export { ArticleDetailsPageLazy } from './ui/ArticleDetailsPage/ArticleDetailsPage.lazy'
export type { ICommentsSchema } from './model/types/commentsSchema'
export type { IArticleDetailsRecommendationsSchema } from './model/types/recommendationsSchema'
export type { IArticleDetailsPageSchema } from './model/types/index'
export { articleDetailsPageReducer } from './model/slice/index'
